package com.calculocomposicoes;

public class Constantes {	
	public static final String INSUMOS_JSON = "[\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 94793,\r\n"
			+ "    \"descricaoComposicao\": \"REGISTRO DE GAVETA BRUTO, LATÃO, ROSCÁVEL, 1 1/4, COM ACABAMENTO E CANOPLA CROMADOS, INSTALADO EM RESERVAÇÃO DE ÁGUA DE EDIFICAÇÃO QUE POSSUA RESERVATÓRIO DE FIBRA/FIBROCIMENTO FORNECIMENTO E INSTALAÇÃO. AF_06/2016\",\r\n"
			+ "    \"unidadeComposicao\": \"UN\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 3148,\r\n"
			+ "    \"descricaoItemComposicao\": \"FITA VEDA ROSCA EM ROLOS DE 18 MM X 50 M (L X C)\",\r\n"
			+ "    \"unidadeItem\": \"UN\",\r\n"
			+ "    \"quantidadeComposicao\": \"0,0190000\",\r\n"
			+ "    \"valorUnitario\": \"9,40\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 94793,\r\n"
			+ "    \"descricaoComposicao\": \"REGISTRO DE GAVETA BRUTO, LATÃO, ROSCÁVEL, 1 1/4, COM ACABAMENTO E CANOPLA CROMADOS, INSTALADO EM RESERVAÇÃO DE ÁGUA DE EDIFICAÇÃO QUE POSSUA RESERVATÓRIO DE FIBRA/FIBROCIMENTO FORNECIMENTO E INSTALAÇÃO. AF_06/2016\",\r\n"
			+ "    \"unidadeComposicao\": \"UN\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 6014,\r\n"
			+ "    \"descricaoItemComposicao\": \"REGISTRO GAVETA COM ACABAMENTO E CANOPLA CROMADOS, SIMPLES, BITOLA 1 1/4  (REF 1509)\",\r\n"
			+ "    \"unidadeItem\": \"UN\",\r\n"
			+ "    \"quantidadeComposicao\": \"1,0000000\",\r\n"
			+ "    \"valorUnitario\": \"100,41\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 94793,\r\n"
			+ "    \"descricaoComposicao\": \"REGISTRO DE GAVETA BRUTO, LATÃO, ROSCÁVEL, 1 1/4, COM ACABAMENTO E CANOPLA CROMADOS, INSTALADO EM RESERVAÇÃO DE ÁGUA DE EDIFICAÇÃO QUE POSSUA RESERVATÓRIO DE FIBRA/FIBROCIMENTO FORNECIMENTO E INSTALAÇÃO. AF_06/2016\",\r\n"
			+ "    \"unidadeComposicao\": \"UN\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 88248,\r\n"
			+ "    \"descricaoItemComposicao\": \"AUXILIAR DE ENCANADOR OU BOMBEIRO HIDRÁULICO COM ENCARGOS COMPLEMENTARES\",\r\n"
			+ "    \"unidadeItem\": \"H\",\r\n"
			+ "    \"quantidadeComposicao\": \"0,7890000\",\r\n"
			+ "    \"valorUnitario\": \"15,19\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 94793,\r\n"
			+ "    \"descricaoComposicao\": \"REGISTRO DE GAVETA BRUTO, LATÃO, ROSCÁVEL, 1 1/4, COM ACABAMENTO E CANOPLA CROMADOS, INSTALADO EM RESERVAÇÃO DE ÁGUA DE EDIFICAÇÃO QUE POSSUA RESERVATÓRIO DE FIBRA/FIBROCIMENTO FORNECIMENTO E INSTALAÇÃO. AF_06/2016\",\r\n"
			+ "    \"unidadeComposicao\": \"UN\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 88267,\r\n"
			+ "    \"descricaoItemComposicao\": \"ENCANADOR OU BOMBEIRO HIDRÁULICO COM ENCARGOS COMPLEMENTARES\",\r\n"
			+ "    \"unidadeItem\": \"H\",\r\n"
			+ "    \"quantidadeComposicao\": \"0,7890000\",\r\n"
			+ "    \"valorUnitario\": \"20,33\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 98561,\r\n"
			+ "    \"descricaoComposicao\": \"IMPERMEABILIZAÇÃO DE PAREDES COM ARGAMASSA DE CIMENTO E AREIA, COM ADITIVO IMPERMEABILIZANTE, E = 2CM. AF_06/2018\",\r\n"
			+ "    \"unidadeComposicao\": \"M2\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 7325,\r\n"
			+ "    \"descricaoItemComposicao\": \"ADITIVO IMPERMEABILIZANTE DE PEGA NORMAL PARA ARGAMASSAS E  CONCRETOS SEM ARMACAO\",\r\n"
			+ "    \"unidadeItem\": \"KG\",\r\n"
			+ "    \"quantidadeComposicao\": \"0,3870000\",\r\n"
			+ "    \"valorUnitario\": \"4,44\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 98561,\r\n"
			+ "    \"descricaoComposicao\": \"IMPERMEABILIZAÇÃO DE PAREDES COM ARGAMASSA DE CIMENTO E AREIA, COM ADITIVO IMPERMEABILIZANTE, E = 2CM. AF_06/2018\",\r\n"
			+ "    \"unidadeComposicao\": \"M2\",\r\n"
			+ "    \"tipoItem\": \"COMPOSICAO\",\r\n"
			+ "    \"codigoItem\": 87286,\r\n"
			+ "    \"descricaoItemComposicao\": \"ARGAMASSA TRAÇO 1:1:6 (CIMENTO, CAL E AREIA MÉDIA) PARA EMBOÇO/MASSA ÚNICA/ASSENTAMENTO DE ALVENARIA DE VEDAÇÃO, PREPARO MECÂNICO COM BETONEIRA 400 L. AF_06/2014\",\r\n"
			+ "    \"unidadeItem\": \"M3\",\r\n"
			+ "    \"quantidadeComposicao\": \"0,0250000\",\r\n"
			+ "    \"valorUnitario\": \"\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 98561,\r\n"
			+ "    \"descricaoComposicao\": \"IMPERMEABILIZAÇÃO DE PAREDES COM ARGAMASSA DE CIMENTO E AREIA, COM ADITIVO IMPERMEABILIZANTE, E = 2CM. AF_06/2018\",\r\n"
			+ "    \"unidadeComposicao\": \"M2\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 88309,\r\n"
			+ "    \"descricaoItemComposicao\": \"PEDREIRO COM ENCARGOS COMPLEMENTARES\",\r\n"
			+ "    \"unidadeItem\": \"H\",\r\n"
			+ "    \"quantidadeComposicao\": \"0,8670000\",\r\n"
			+ "    \"valorUnitario\": \"19,82\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 98561,\r\n"
			+ "    \"descricaoComposicao\": \"IMPERMEABILIZAÇÃO DE PAREDES COM ARGAMASSA DE CIMENTO E AREIA, COM ADITIVO IMPERMEABILIZANTE, E = 2CM. AF_06/2018\",\r\n"
			+ "    \"unidadeComposicao\": \"M2\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 88316,\r\n"
			+ "    \"descricaoItemComposicao\": \"SERVENTE COM ENCARGOS COMPLEMENTARES\",\r\n"
			+ "    \"unidadeItem\": \"H\",\r\n"
			+ "    \"quantidadeComposicao\": \"0,1760000\",\r\n"
			+ "    \"valorUnitario\": \"14,78\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 87286,\r\n"
			+ "    \"descricaoComposicao\": \"ARGAMASSA TRAÇO 1:1:6 (CIMENTO, CAL E AREIA MÉDIA) PARA EMBOÇO/MASSA ÚNICA/ASSENTAMENTO DE ALVENARIA DE VEDAÇÃO, PREPARO MECÂNICO COM BETONEIRA 400 L. AF_06/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"M3\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 370,\r\n"
			+ "    \"descricaoItemComposicao\": \"AREIA MEDIA - POSTO JAZIDA/FORNECEDOR (RETIRADO NA JAZIDA, SEM TRANSPORTE)\",\r\n"
			+ "    \"unidadeItem\": \"M3\",\r\n"
			+ "    \"quantidadeComposicao\": \"1,3000000\",\r\n"
			+ "    \"valorUnitario\": \"67,50\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 87286,\r\n"
			+ "    \"descricaoComposicao\": \"ARGAMASSA TRAÇO 1:1:6 (CIMENTO, CAL E AREIA MÉDIA) PARA EMBOÇO/MASSA ÚNICA/ASSENTAMENTO DE ALVENARIA DE VEDAÇÃO, PREPARO MECÂNICO COM BETONEIRA 400 L. AF_06/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"M3\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 1106,\r\n"
			+ "    \"descricaoItemComposicao\": \"CAL HIDRATADA CH-I PARA ARGAMASSAS\",\r\n"
			+ "    \"unidadeItem\": \"KG\",\r\n"
			+ "    \"quantidadeComposicao\": \"130,4900000\",\r\n"
			+ "    \"valorUnitario\": \"0,47\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 87286,\r\n"
			+ "    \"descricaoComposicao\": \"ARGAMASSA TRAÇO 1:1:6 (CIMENTO, CAL E AREIA MÉDIA) PARA EMBOÇO/MASSA ÚNICA/ASSENTAMENTO DE ALVENARIA DE VEDAÇÃO, PREPARO MECÂNICO COM BETONEIRA 400 L. AF_06/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"M3\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 1379,\r\n"
			+ "    \"descricaoItemComposicao\": \"CIMENTO PORTLAND COMPOSTO CP II-32\",\r\n"
			+ "    \"unidadeItem\": \"KG\",\r\n"
			+ "    \"quantidadeComposicao\": \"250,1100000\",\r\n"
			+ "    \"valorUnitario\": \"0,49\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 87286,\r\n"
			+ "    \"descricaoComposicao\": \"ARGAMASSA TRAÇO 1:1:6 (CIMENTO, CAL E AREIA MÉDIA) PARA EMBOÇO/MASSA ÚNICA/ASSENTAMENTO DE ALVENARIA DE VEDAÇÃO, PREPARO MECÂNICO COM BETONEIRA 400 L. AF_06/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"M3\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 88377,\r\n"
			+ "    \"descricaoItemComposicao\": \"OPERADOR DE BETONEIRA ESTACIONÁRIA/MISTURADOR COM ENCARGOS COMPLEMENTARES\",\r\n"
			+ "    \"unidadeItem\": \"H\",\r\n"
			+ "    \"quantidadeComposicao\": \"1,0000000\",\r\n"
			+ "    \"valorUnitario\": \"16,00\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 87286,\r\n"
			+ "    \"descricaoComposicao\": \"ARGAMASSA TRAÇO 1:1:6 (CIMENTO, CAL E AREIA MÉDIA) PARA EMBOÇO/MASSA ÚNICA/ASSENTAMENTO DE ALVENARIA DE VEDAÇÃO, PREPARO MECÂNICO COM BETONEIRA 400 L. AF_06/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"M3\",\r\n"
			+ "    \"tipoItem\": \"COMPOSICAO\",\r\n"
			+ "    \"codigoItem\": 88830,\r\n"
			+ "    \"descricaoItemComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - CHP DIURNO. AF_10/2014\",\r\n"
			+ "    \"unidadeItem\": \"CHP\",\r\n"
			+ "    \"quantidadeComposicao\": \"1,1900000\",\r\n"
			+ "    \"valorUnitario\": \"\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 87286,\r\n"
			+ "    \"descricaoComposicao\": \"ARGAMASSA TRAÇO 1:1:6 (CIMENTO, CAL E AREIA MÉDIA) PARA EMBOÇO/MASSA ÚNICA/ASSENTAMENTO DE ALVENARIA DE VEDAÇÃO, PREPARO MECÂNICO COM BETONEIRA 400 L. AF_06/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"M3\",\r\n"
			+ "    \"tipoItem\": \"COMPOSICAO\",\r\n"
			+ "    \"codigoItem\": 88831,\r\n"
			+ "    \"descricaoItemComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - CHI DIURNO. AF_10/2014\",\r\n"
			+ "    \"unidadeItem\": \"CHI\",\r\n"
			+ "    \"quantidadeComposicao\": \"3,9100000\",\r\n"
			+ "    \"valorUnitario\": \"\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 88830,\r\n"
			+ "    \"descricaoComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - CHP DIURNO. AF_10/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"CHP\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 88826,\r\n"
			+ "    \"descricaoItemComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - DEPRECIAÇÃO. AF_10/2014\",\r\n"
			+ "    \"unidadeItem\": \"H\",\r\n"
			+ "    \"quantidadeComposicao\": \"1,0000000\",\r\n"
			+ "    \"valorUnitario\": \"0,18\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 88830,\r\n"
			+ "    \"descricaoComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - CHP DIURNO. AF_10/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"CHP\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 88827,\r\n"
			+ "    \"descricaoItemComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - JUROS. AF_10/2014\",\r\n"
			+ "    \"unidadeItem\": \"H\",\r\n"
			+ "    \"quantidadeComposicao\": \"1,0000000\",\r\n"
			+ "    \"valorUnitario\": \"0,04\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 88830,\r\n"
			+ "    \"descricaoComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - CHP DIURNO. AF_10/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"CHP\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 88828,\r\n"
			+ "    \"descricaoItemComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - MANUTENÇÃO. AF_10/2014\",\r\n"
			+ "    \"unidadeItem\": \"H\",\r\n"
			+ "    \"quantidadeComposicao\": \"1,0000000\",\r\n"
			+ "    \"valorUnitario\": \"0,17\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 88830,\r\n"
			+ "    \"descricaoComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - CHP DIURNO. AF_10/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"CHP\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 88829,\r\n"
			+ "    \"descricaoItemComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - MATERIAIS NA OPERAÇÃO. AF_10/2014\",\r\n"
			+ "    \"unidadeItem\": \"H\",\r\n"
			+ "    \"quantidadeComposicao\": \"1,0000000\",\r\n"
			+ "    \"valorUnitario\": \"0,86\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 88831,\r\n"
			+ "    \"descricaoComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - CHI DIURNO. AF_10/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"CHI\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 88826,\r\n"
			+ "    \"descricaoItemComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - DEPRECIAÇÃO. AF_10/2014\",\r\n"
			+ "    \"unidadeItem\": \"H\",\r\n"
			+ "    \"quantidadeComposicao\": \"1,0000000\",\r\n"
			+ "    \"valorUnitario\": \"0,18\"\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"codigoComposicao\": 88831,\r\n"
			+ "    \"descricaoComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - CHI DIURNO. AF_10/2014\",\r\n"
			+ "    \"unidadeComposicao\": \"CHI\",\r\n"
			+ "    \"tipoItem\": \"INSUMO\",\r\n"
			+ "    \"codigoItem\": 88827,\r\n"
			+ "    \"descricaoItemComposicao\": \"BETONEIRA CAPACIDADE NOMINAL DE 400 L, CAPACIDADE DE MISTURA 280 L, MOTOR ELÉTRICO TRIFÁSICO POTÊNCIA DE 2 CV, SEM CARREGADOR - JUROS. AF_10/2014\",\r\n"
			+ "    \"unidadeItem\": \"H\",\r\n"
			+ "    \"quantidadeComposicao\": \"1,0000000\",\r\n"
			+ "    \"valorUnitario\": \"0,04\"\r\n"
			+ "  }\r\n"
			+ "]\r\n"
			+ "";
	
	
}
